<?php
return [
    'API_APPLICATION_KEY' => 'A9E6E8ED76CE1C994C3C7FD95E855',
    'socket_port' => 2024,
    'USER_REFERRAL_CODE_SIZE' => 8,
    'CREDITED' => 'Credited',
    'DEBITED' => 'Debited',
    'WHT_AMOUNT_CREDITED' => 'WALLET_ADD',
    'WHT_AMOUNT_DEBITED' => 'WALLET_DEBITED',
    'WH_BONUS_TEMPLATE' => 'Bonus',
    'WH_USER_WALLET_AMOUNT_ADDED_BY_ADMIN' => 'Admin',
    'WH_USER_WALLET_AMOUNT_DEDUCTED_BY_ADMIN' => 'Admin',
    'WH_USER_WALLET_AMOUNT_ADDED' => 'Amount Added',
    'purchase_success' => 'Purchase successfully',
    'purchase_fail' => 'Purchase Fails',
    'notification_types' => [
        'general'=>'general',
    ],
    'datatable_length_menu' => '[[10, 25, 50, 100, 200, 500, -1],[10, 25, 50, 100, 200, 500, "All"]]',
    'game_status' => [
        'CREATED',
        'STARTED',
        'COMPLETED',
        'CANCELLED'
    ],
    'leaderboard_records_count' => 20,
    'payment_status' => ['FAILED','PENDING','SUCCESS'],
    'date_filter_options' => [''=>'All', 'TODAY'=>'Today', 'YESTERDAY'=>'Yesterday', 'LAST_7_DAYS'=>'Last 7 Days', 'LAST_30_DAYS'=>'Last 30 Days', 'THIS_WEEK'=>'This Week', 'THIS_MONTH'=>'This Month', 'PREVIOUS_WEEK'=>'Previous Week', 'PREVIOUS_MONTH'=>'Previous Month', 'THIS_YEAR'=>'This Year', 'PREVIOUS_YEAR'=>'Previous Year', 'CUSTOM'=>'Custom Dates'],
    'game_keys' => ['bluboy_runner'=>'Bluboy Runner', 'candy_crush'=>'Candy Crush', 'fruit_ninja'=>'Fruit Ninja'],
    'gameplay_players_count' => 2,
    'SMS91_AUTHKEY' => env('SMS91_AUTHKEY', ''),
    'SMS91_SENDERID' => env('SMS91_SENDERID', ''),
    'MSG91_COMPANY_NAME' => env('MSG91_COMPANY_NAME', ''),
    'MSG91_TEMPLATE_ID' => env('MSG91_TEMPLATE_ID', ''),
    'SMS91_API_URL' => env('SMS91_API_URL', 'http://api.msg91.com/api/sendhttp.php'),
    'currency' => 'INR',
    'cashfree_webhook_url' => config('app.url').'/webhook/cashfree_payment_webhook',
    'cashfree_payout_webhook_url' => config('app.url').'/webhook/cashfree_payout_webhook',
];
